export const lectures = [
  {
    id: "1",
    title: "The Early Years in Makkah",
    description: "Life in the desert and noble upbringing",
    duration: "45 mins",
    audio: require("../assets/audio/sira2.mp3"),
    playing: false,
  },
  {
    id: "2",
    title: "The First Revelation",
    description: "Cave Hira and the beginning of...",
    duration: "38 mins",
    audio: require("../assets/audio/sira2.mp3"),
    playing: false,
  },
  {
    id: "3",
    title: "Public Preaching",
    description: "Calling the people of Makkah to Islam...",
    duration: "42 mins",
    audio: require("../assets/audio/sira2.mp3"),
    playing: false,
  },
  {
    id: "4",
    title: "The Migration to Abyssinia",
    description: "Seeking refuge from persecution in a just land",
    duration: "50 mins",
    audio: require("../assets/audio/sira2.mp3"),
    playing: false,
  },
  {
    id: "5",
    title: "The Year of Sorrow",
    description: "The loss of Khadijah (RA) and Abu Talib",
    duration: "55 mins",
    audio: require("../assets/audio/sira2.mp3"),
    playing: false,
  },
  {
    id: "6",
    title: "Isra and Mi'raj",
    description: "The Night Journey and Ascension",
    duration: "60 mins",
    audio: require("../assets/audio/sira2.mp3"),
    playing: false,
  },
  {
    id: "7",
    title: "Hijrah to Medina",
    description:
      "The migration to Medina and establishment of the Muslim community",
    duration: "60 mins",
    audio: require("../assets/audio/sira2.mp3"),
    playing: false,
  },
];
